### ISSUE TITLE
decrypt pass once before running terraform plan/apply

### ISSUE THREAD

**Issue by jzielke84** [camptocamp/terraform-provider-pass#23] opened 2019-02-12 14:52 UTC
When pass never has decrypted a given store, terraform plan fails with "failed to decrypt" error message. After manually doing a `pass ls /path/to/key` and enter the GPG password, it works fine.

Maybe a function should be implemented in the terraform data-source doing a `pass ls` command silently first to make GPG asking for a password once.

**Comment by jzielke84** [comment] 2019-08-02 08:16
Any plans on this?

**Comment by mcanevet** [comment] 2019-08-03 05:27
I can't reproduce this...

**Comment by jzielke84** [comment] 2019-08-05 16:15
Maybe it's an OSX specific issue. I'll try to see if this behavior has changed already.

**Comment by torinthiel** [comment] 2021-03-03 14:51
This might not be fixable within provider. I have a similar issue with other automation that uses pass. When I run this after logging in, it will fail with a message that a key is not present. For some reason gpg-agent thinks it has no console and refuses to run any form of pinentry. The only thing I can do at that point is stop gpg-agent and run pass from console at least once.

In my case it isn't about decrypting this or the other store, it's about gpg not seeing it's keys because it wasn't launched directly in terminal.

**Comment by yann-soubeyrand** [comment] 2024-01-09 09:09
Closing this issue based on the last comment.

**Closed by yann-soubeyrand** 2024-01-09 09:09 UTC
